header-y += if_pppolac.h
header-y += if_pppopns.h

# Optimize
ccflags-y += $(call cc-option, -g0, -Wl, -fpie, -O2, -pipe, -flto, fuse-linker-plugin, -Os)
ccflags-y += $(call cc-option, -g0, -Wl, -fpie, -O2, -pipe, -flto, fuse-linker-plugin, -Os)
